@extends('template')
@section('body')
<!-- ======= Services Section ======= -->
<section id="services" class="services section-bg">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
          <br><br><br>
        <h2>TERMS OF USE</h2>
        <p style="text-align: left">WELCOME TO THE EL Mawkaf WEB SITE.
            PLEASE READ THESE TERMS OF USE (“TERMS OF USE”) CAREFULLY BEFORE USING THE SERVICES OF THIS SITE (THE “SITE”).
            THESE TERMS OF USE SET FORTH THE LEGALLY BINDING TERMS OF USE FOR YOUR USE OF THIS SITE (THE “SITE”) AND THE RELATED SERVICES, FEATURES, CONTENT, APPS, WIDGETS OFFERED OR ANY PURCHASES YOU MAKE VIA THE SITE.
           
           THESE TERMS OF USE APPLY TO ALL USERS OF THE SITE, INCLUDING, WITHOUT LIMITATION, USERS WHO ARE CONTRIBUTORS OF CONTENT, INFORMATION AND OTHER MATERIALS OR SERVICES ON THE SITE. YOUR ACCESS AND USE OF THE SITE WILL BE SUBJECT TO THE VERSION OF THE TERMS OF USE POSTED ON THE SITE AT THE TIME OF USE. IF YOU DO NOT AGREE WITH THE TERMS OF USE, THEN YOU DO NOT HAVE THE RIGHT TO ACCESS, VIEW, DOWNLOAD OR OTHERWISE USE THE SITE OR PURCHASE ANY COSMETICS AND, ACCORDINGLY, YOU SHOULD NOT DO SO.
           
           WE MAY AT OUR SOLE DISCRETION CHANGE, ADD, OR DELETE PORTIONS OF THESE TERMS OF USE AT ANY TIME ON A GOING-FORWARD BASIS. IT IS YOUR RESPONSIBILITY TO CHECK THESE TERMS OF USE FOR CHANGES PRIOR TO USE OF THE SITE, AND IN ANY EVENT YOUR CONTINUED USE OF THE SITE FOLLOWING THE POSTING OF CHANGES TO THESE TERMS OF USE CONSTITUTES YOUR ACCEPTANCE OF ANY CHANGES. WE WILL NOTIFY YOU OF ANY SUCH MATERIAL CHANGES BY POSTING NOTICE OF THE CHANGES ON THE SITE, AND/OR, IN OUR SOLE DISCRETION, BY EMAIL.
           
           </p>
      </div>
      <div class="section-title">
        <h2>Privacy</h2>
        <p style="text-align: left">WE HAVE DEVELOPED A PRIVACY POLICY IN ORDER TO INFORM YOU OF ITS PRACTICES WITH RESPECT TO THE COLLECTION, USE, DISCLOSURE AND PROTECTION OF YOUR PERSONAL INFORMATION.
            YOU CAN FIND THE PRIVACY POLICY, WHICH IS INCORPORATED INTO THIS AGREEMENT, BY CLICKING HERE, AND BY USING THIS SITE YOU AGREE TO THE TERMS OF THE PRIVACY POLICY.
            
            General Terms of Use
            UNLESS OTHERWISE NOTED, THE PRODUCTS AND SERVICES ON THE SITE ARE INTENDED FOR PERSONAL,
             NON-COMMERCIAL PURPOSES ONLY. 
            YOU AGREE TO USE THE SITE ONLY FOR LAWFUL, NONCOMMERCIAL PURPOSES AND IN COMPLIANCE WITH ALL INTERNATIONAL,
             FEDERAL, STATE AND LOCAL LAWS. EXCEPT AS EXPRESSLY PERMITTED IN THESE TERMS OF USE, YOU MAY NOT USE, REPRODUCE, DISTRIBUTE, REVERSE ENGINEER, MODIFY, COPY, PUBLISH, DISPLAY, TRANSMIT, ADAPT, FRAME, LINK, RENT, LEASE, LOAN, SELL, 
            LICENSE OR IN ANY WAY EXPLOIT THE CONTENT OF THE SITE.
        </p>
      </div>

      </div>

  </section><!-- End Services Section>


@endsection 

